### ISSUE TITLE
clarification on "roosting reclassification" code section

### ISSUE THREAD

**Issue by bcaneco** [dmpstats/Behavioural_Classification_for_Vultures#3]
Hi @callumjclarke  and @lindesaysh, apologies for bombarding you with questions, but I'm trying to get my head around the classification code and it would be great to clarify some bits of it. This one relates to the chunk below:

https://github.com/dmpstats/Behavioural_Classification_for_Vultures/blob/b0940de04d96b0899c09ea9b58eead57ff5b30f7/RFunction.R#L328-L390

Basically, I couldn't figure out the utility of lines L328 - L369, as columns `roostsite` (and thus cols `endofday_dist` and `endofday`) are not involved in anywhere in the reclassification, before being dropped out in L385 and L390.

Is there any hidden code involving these columns in the updating of `behav` that e.g. has not been pushed to the repo? Or can we delete L328 - L369 altogether?

Thanks

**Comment by callumjclarke** [comment]
Well spotted 😄 I'd branched this to improve it but forgotten to make the pull request. Pull request now sent with the new and faster overnight-distance calculations, which shouldn't have this problem

**Comment by bcaneco** [comment]
Cool, thanks Callum!

**Comment by bcaneco** [comment]
Hi Callum, me again, sorry. 

Having a look at the code in branch under the pull request (ACC-&-Roost-Changes), my question sill stands:  columns `roostsite` (and thus cols `endofday_dist and `endofday`) are not involved anywhere in the reclassification, before being dropped out in L385 and L390.

https://github.com/dmpstats/Behavioural_Classification_for_Vultures/blob/d3cca246bf41d981e2e708195325b1c3cc4516ab/RFunction.R#L329-L391

Any other bit of code tucked away in a hidden corner somewhere? Otherwise I'm struggling to see the relevance of computations in L329:L369.

**Comment by callumjclarke** [comment]
Hi @bcaneco you're absolutely right, my fault! It's missing the correct re-classification statement, which should re-classify only groups in which `roostsite != 0` for at least one location (except for `STravelling` locations) . This is the corrected version of L372-L390:


```
  #  Calculate cumulative travel and reverse cumulative travel per day
  data %<>%
    group_by(mt_track_id(.), date(mt_time(.))) %>%
    mutate(travel01 = ifelse(stationary == T, 0, 1)) %>%
    mutate(cum_trav = cumsum(travel01),
           revcum_trav = spatstat.utils::revcumsum(travel01)) %>%
    ungroup() %>%
    mutate(
      # Generate runs of stationary behaviour before/after final/first location:
           roostgroup = ifelse(cum_trav == 0 | revcum_trav == 0, 1, 0),
           roostgroup = rleid(roostgroup),
           roostgroup = ifelse(cum_trav != 0 & revcum_trav != 0, NA, roostgroup)
           ) %>%
    group_by(roostgroup) %>%
    #dplyr::select(-c("travel01", "cum_trav", "revcum_trav", "endofday_dist")) %>%
    mutate(
      # Reclassify these runs as roosting
      behav = ifelse(!is.na(roostgroup) & any(roostsite == 1) & (behav != "STravelling"), "SRoosting", behav)
    ) %>%
    dplyr::select(-c("endofday", "roostsite", "mt_track_id(.)", "date(mt_time(.))")) %>%
    ungroup()
```

Almost entirely the same, but now locations only become Roosting when
- they are contained within a `roostgroup`
- they are not `STravelling`
- at least one overnight location within this `roostgroup` is a roost-site (i.e. `endofday_dist < 25`)

I've spoken to @lindesaysh and we're going to re-arrange a few of the re-classification steps (so that the roost-grouping is the final re-classification to take place, apart from perhaps cumulative time stationary). I'll make some changes over the next few days and send over a pull request

**Comment by bcaneco** [comment]
Ah right, that makes **a bit** more sense! 😄 Thanks - I think it's wise to wait for those re-arrangements before continuing with the code review.
